apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-04-26T17:57:42Z"
  labels:
    app: aceest-green
  name: aceest-green
  namespace: default
  resourceVersion: "1775"
  uid: 9a7148cc-4e1b-4fdc-b36f-3591e771b654
spec:
  clusterIP: 10.103.249.23
  clusterIPs:
  - 10.103.249.23
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32182
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: aceest-green
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
